CREATE DATABASE HMS
GO
USE HMS
GO
CREATE OR ALTER PROC CREATE_TABLE
AS
BEGIN TRAN
    BEGIN TRY
        CREATE TABLE PATIENT
        (
            ID CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            PhoneNumber CHAR(10),
            Pass VARCHAR(32),
            UserName NVARCHAR(64),
            Dob DATE,
            UserAddress NVARCHAR(128),
            Islock BIT DEFAULT 0
        )

        CREATE TABLE STAFF
        (
            ID CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            PhoneNumber CHAR(10),
            Pass VARCHAR(32),
            UserName NVARCHAR(64),
            Dob DATE,
            UserAddress NVARCHAR(128) DEFAULT NULL,
            Islock BIT DEFAULT 0
        )

        CREATE TABLE USER_ADMIN
        (
            ID CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            PhoneNumber CHAR(10),
            Pass VARCHAR(32),
            Dob DATE,
            UserAddress NVARCHAR(128) DEFAULT NULL,
            UserName NVARCHAR(64),
        )

        CREATE TABLE DENTIST
        (
            ID CHAR(16) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 16),
            PhoneNumber CHAR(10),
            Pass VARCHAR(32),
            UserName NVARCHAR(64),
            Dob DATE,
            UserAddress NVARCHAR(128) DEFAULT NULL,
            Islock BIT DEFAULT 0
        )

        CREATE TABLE APPOINTMENT
        (
            ID_PATIENT CHAR(16),
            ID_DENTIST CHAR(16),
            DATE_OF_APPOINTMENT DATE,
            TIME_OF_APPOINTMENT TIME
        )

        CREATE TABLE SCHEDULE
        (
            ID_DENTIST CHAR(16),
            DATE_OF_APPOINTMENT DATE,
            TIME_OF_APPOINTMENT TIME
        )

        CREATE TABLE RECORD
        (
            ID CHAR(13) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 13),
            ID_PATIENT CHAR(16),
            ID_DENTIST CHAR(16),
            DATE_OF_APPOINTMENT DATE,
            TIME_OF_APPOINTMENT TIME,
            TOTAL BIGINT DEFAULT 0,
            DIAGNOSE NVARCHAR(512),
            SYMPTOM NVARCHAR(512),
        )

        CREATE TABLE PRESCRIPTION
        (
            ID_RECORD CHAR(13),
            ID_BATCH CHAR(12),
            ID_DRUG CHAR(10),
            QUANTITY INT,
            DESCRIPTION_ NVARCHAR(32),
            TOTAL INT
        )

        CREATE TABLE SERVICEINDICATOR
        (
            ID_RECORD CHAR(13),
            ID_SERVICE CHAR(9),
            TOTAL INT
        )

        CREATE TABLE SERVICE
        (
            ID CHAR(9) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 9),
            SERVICENAME NVARCHAR(64),
            PRICE INT,
            IsDELETE BIT DEFAULT(0)
        )

        CREATE TABLE DRUG
        (
            ID_BATCH CHAR(12) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 12),
            ID_DRUG CHAR(10) DEFAULT SUBSTRING(CONVERT(CHAR(36), NEWID()), 1, 10),
            DRUGNAME NVARCHAR(32),
            UNIT VARCHAR(10),
            INDICATOR NVARCHAR(128),
            QUANTITY INT,
            EXPIRE_DATE DATE,
            PRICE INT,
            IsDELETE BIT DEFAULT(0)
        )
    

        /*NOT NULL */
        --R21
        ALTER TABLE PATIENT ALTER COLUMN ID CHAR(16) NOT NULL;
        ALTER TABLE PATIENT ALTER COLUMN PhoneNumber CHAR(10) NOT NULL;
        ALTER TABLE PATIENT ALTER COLUMN UserName NVARCHAR(64) NOT NULL;

        --R22
        ALTER TABLE STAFF ALTER COLUMN ID CHAR(16) NOT NULL;
        ALTER TABLE STAFF ALTER COLUMN PhoneNumber CHAR(10) NOT NULL;
        ALTER TABLE STAFF ALTER COLUMN UserName NVARCHAR(64) NOT NULL;

        --R23
        ALTER TABLE DENTIST ALTER COLUMN ID CHAR(16) NOT NULL;
        ALTER TABLE DENTIST ALTER COLUMN PhoneNumber CHAR(16) NOT NULL;
        ALTER TABLE DENTIST ALTER COLUMN UserName NVARCHAR(64) NOT NULL;

        --R24
        ALTER TABLE USER_ADMIN ALTER COLUMN ID CHAR(16) NOT NULL;
        ALTER TABLE USER_ADMIN ALTER COLUMN PhoneNumber CHAR(10) NOT NULL;
        ALTER TABLE USER_ADMIN ALTER COLUMN UserName NVARCHAR(64) NOT NULL;

        --R25
        ALTER TABLE APPOINTMENT ALTER COLUMN ID_DENTIST CHAR(16) NOT NULL;
        ALTER TABLE APPOINTMENT ALTER COLUMN ID_PATIENT CHAR(16) NOT NULL;
        ALTER TABLE APPOINTMENT ALTER COLUMN DATE_OF_APPOINTMENT DATE NOT NULL;
        ALTER TABLE APPOINTMENT ALTER COLUMN TIME_OF_APPOINTMENT TIME NOT NULL;

        --R26
        ALTER TABLE SCHEDULE ALTER COLUMN ID_DENTIST CHAR(16) NOT NULL;
        ALTER TABLE SCHEDULE ALTER COLUMN DATE_OF_APPOINTMENT DATE NOT NULL;
        ALTER TABLE SCHEDULE ALTER COLUMN TIME_OF_APPOINTMENT TIME NOT NULL;

        --R27
        ALTER TABLE PRESCRIPTION ALTER COLUMN QUANTITY INT NOT NULL;
        ALTER TABLE PRESCRIPTION ALTER COLUMN DESCRIPTION_ NVARCHAR(32) NOT NULL;
        ALTER TABLE PRESCRIPTION ALTER COLUMN ID_RECORD CHAR(13) NOT NULL;
        ALTER TABLE PRESCRIPTION ALTER COLUMN ID_BATCH CHAR(12) NOT NULL;
        ALTER TABLE PRESCRIPTION ALTER COLUMN ID_DRUG CHAR(10) NOT NULL;

        --R28
        ALTER TABLE RECORD ALTER COLUMN ID CHAR(13) NOT NULL;

        --R29
        ALTER TABLE SERVICEINDICATOR ALTER COLUMN ID_RECORD CHAR(13) NOT NULL;
        ALTER TABLE SERVICEINDICATOR ALTER COLUMN ID_SERVICE CHAR(9) NOT NULL;

        --R30
        ALTER TABLE SERVICE ALTER COLUMN ID CHAR(9) NOT NULL;

        --R31
        ALTER TABLE DRUG ALTER COLUMN DRUGNAME NVARCHAR(32) NOT NULL;
        ALTER TABLE DRUG ALTER COLUMN ID_BATCH CHAR(12) NOT NULL;
        ALTER TABLE DRUG ALTER COLUMN QUANTITY CHAR(8) NOT NULL;
        ALTER TABLE DRUG ALTER COLUMN PRICE CHAR(8) NOT NULL;
        ALTER TABLE DRUG ALTER COLUMN EXPIRE_DATE DATE NOT NULL;
        ALTER TABLE DRUG ALTER COLUMN ID_DRUG CHAR(10) NOT NULL;

        /*UNIQUE*/
        --R1
        ALTER TABLE USER_ADMIN ADD UNIQUE (PhoneNumber);

        --R2
        ALTER TABLE PATIENT ADD UNIQUE (PhoneNumber);

        --R3
        ALTER TABLE STAFF ADD UNIQUE (PhoneNumber);

        --R4
        ALTER TABLE DENTIST ADD UNIQUE (PhoneNumber);

        ALTER TABLE SERVICE ADD UNIQUE (SERVICENAME);

        /*Add primary key*/
        --R5
        ALTER TABLE PATIENT ADD PRIMARY KEY (ID);

        --R6
        ALTER TABLE STAFF ADD PRIMARY KEY (ID);

        --R7
        ALTER TABLE USER_ADMIN ADD PRIMARY KEY (ID);

        --R8
        ALTER TABLE DENTIST ADD PRIMARY KEY (ID);

        --R9
        ALTER TABLE APPOINTMENT ADD PRIMARY KEY (ID_DENTIST, DATE_OF_APPOINTMENT, TIME_OF_APPOINTMENT);

        --R10
        ALTER TABLE SCHEDULE ADD PRIMARY KEY (ID_DENTIST, DATE_OF_APPOINTMENT, TIME_OF_APPOINTMENT);

        --R11
        ALTER TABLE RECORD ADD PRIMARY KEY (ID);

        --R12
        ALTER TABLE PRESCRIPTION ADD PRIMARY KEY (ID_RECORD, ID_BATCH, ID_DRUG);

        --13
        ALTER TABLE SERVICEINDICATOR ADD PRIMARY KEY (ID_RECORD, ID_SERVICE);

        --R14
        ALTER TABLE SERVICE ADD PRIMARY KEY (ID);

        --R15
        ALTER TABLE DRUG ADD PRIMARY KEY (ID_BATCH, ID_DRUG);

        -- ADD FOREIGN KEY
        --R16
        ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID);

        --R51
        ALTER TABLE APPOINTMENT ADD CONSTRAINT FK_APPOINTMENT_SCHEDULE FOREIGN KEY (ID_DENTIST, DATE_OF_APPOINTMENT, TIME_OF_APPOINTMENT) REFERENCES SCHEDULE(ID_DENTIST, DATE_OF_APPOINTMENT, TIME_OF_APPOINTMENT);

        --R17
        ALTER TABLE PRESCRIPTION ADD CONSTRAINT FK_PRESCRIPTION_RECORD FOREIGN KEY (ID_RECORD) REFERENCES RECORD(ID);
        ALTER TABLE PRESCRIPTION ADD CONSTRAINT FK_PRESCRIPTION_DRUG FOREIGN KEY (ID_BATCH, ID_DRUG) REFERENCES DRUG(ID_BATCH, ID_DRUG);

        --R18
        ALTER TABLE SERVICEINDICATOR ADD CONSTRAINT FK_SERVICEINDICATOR_RECORD FOREIGN KEY (ID_RECORD) REFERENCES RECORD(ID);
        ALTER TABLE SERVICEINDICATOR ADD CONSTRAINT FK_SERVICEINDICATOR_SERVICE FOREIGN KEY (ID_SERVICE) REFERENCES SERVICE(ID);

        --R19
        ALTER TABLE SCHEDULE ADD CONSTRAINT FK_SCHEDULE_DENTIST FOREIGN KEY (ID_DENTIST) REFERENCES DENTIST(ID);

        --R20
        ALTER TABLE RECORD ADD CONSTRAINT FK_RECORD_APPOINTMENT FOREIGN KEY (ID_DENTIST, DATE_OF_APPOINTMENT, TIME_OF_APPOINTMENT) REFERENCES APPOINTMENT(ID_DENTIST, DATE_OF_APPOINTMENT, TIME_OF_APPOINTMENT);

        --R32
        ALTER TABLE PATIENT ADD CHECK (DATEDIFF(yy, Dob,  GETDATE()) >= 6)

        --R33
        ALTER TABLE DRUG ADD CHECK (QUANTITY >= 0)
END TRY
    BEGIN CATCH
        ROLLBACK TRAN
        THROW
    END CATCH
COMMIT

GO
EXEC CREATE_TABLE