import { RolesBuilder } from 'nest-access-control';
import { Role } from './enum';

export const RBAC_POLICY: RolesBuilder = new RolesBuilder();

// prettier-ignore
RBAC_POLICY
.grant(Role.Guest)
    .createAny('patient')
    .createAny('dentist')
    .createAny('staff')
    .createAny('appointment')
    .createAny('admin')
    .readAny('schedule')
    .readAny('appointment')
    .readAny('dentist')
.grant(Role.Patient)
    .extend(Role.Guest)
    .createOwn('appointment')
    .readOwn('appointment')
    .updateOwn('appointment')
    .deleteOwn('appointment')
.grant(Role.Dentist)
    .extend(Role.Guest)
    .readOwn('schedule')
    .createOwn('appointment')
    .readAny('appointment')
    .readOwn('appointment')
    .updateOwn('appointment')
    .deleteOwn('appointment')
.grant(Role.Staff)
    .extend(Role.Guest)
    .createAny('appointment')
    .readAny('appointment')
    .updateAny('appointment')
    .deleteAny('appointment')
.grant(Role.Admin)
    .extend(Role.Guest)
    .createAny('appointment')
    .readAny('appointment')
    .updateAny('appointment')
    .deleteAny('appointment')
    .createAny('dentist')
    .readAny('dentist')
    .updateAny('dentist')
    .deleteAny('dentist')
    .createAny('patient')
    .readAny('patient')
    .updateAny('patient')
    .deleteAny('patient')
    .createAny('staff')
    .readAny('staff')
    .updateAny('staff')
    .deleteAny('staff');

